### ISSUE TITLE
메인페이지 제목 중앙 정렬 

### ISSUE THREAD

**Issue by Ivoryeee** [LikelionUniv/LikelionUniv_Frontend_University#61]
### ✨ 기능 리스트

---

- 메인페이지의 제목을 가운데 정렬 가능하도록 변경

### ✏ 사용 이유

---

- 카카오톡으로 웹사이트 접속 시, 일부 디바이스에서 제목 가운데 정렬 안됨
=> 제목 가운데 정렬 가능하도록 변경

![멋대 이슈](https://github.com/LikelionUniv/LikelionUniv_Frontend_University/assets/105477246/2e78d1dd-54c4-436b-bcc5-62b593d45295)

**Comment by KimKyuHoi** [comment]
이슈 조금 더 깔끔하게 쓰는게 더 좋을 꺼 같아서 약간 위치만 수정했습니다!
