### ISSUE TITLE
super admin 대학 검색기능 오류

### ISSUE THREAD

**Issue by eastfilmm** [LikelionUniv/LikelionUniv_Frontend_University#62]
### ✨ 기능 리스트

---

- 처음 대학교 검색 페이지에서 
url 에서 page=!1 일때
대학교 검색 시 page=1 로 초기화 되지 않고 이전의 page 넘버로 가지고있는 문제

### ✏ 사용 이유

---

![image](https://github.com/LikelionUniv/LikelionUniv_Frontend_University/assets/91816664/afb64774-6ff3-43d8-8074-599c7beef535)
![image](https://github.com/LikelionUniv/LikelionUniv_Frontend_University/assets/91816664/fb13e616-d41b-4bea-b64b-deb31f87a389)
![image](https://github.com/LikelionUniv/LikelionUniv_Frontend_University/assets/91816664/02f37800-a002-49e3-b64c-23110087d8a5)
![image](https://github.com/LikelionUniv/LikelionUniv_Frontend_University/assets/91816664/bf99c544-eae5-41a1-a711-8e721821ec53)
![image](https://github.com/LikelionUniv/LikelionUniv_Frontend_University/assets/91816664/e65e356a-a405-4526-bcbf-f463164bcfc4)

처음 대학교 검색 페이지에서 
url 에서 page=!1 일때
대학교 검색 시 page=1 로 초기화 되지 않고 이전의 page 넘버로 가지고있는 문제

**Comment by KimKyuHoi** [comment]
이것도 나중에 통일성 이유로 위치만 잠깐 수정했습니다!
